services:
  - type: web
    name: ams-tea-traders
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn amstea.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
